### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [loia5tqd001/DevC-React-Native-Weekly-Assignments#1]
Just minor thing: Array Length must be limit to small number , your input allow over 10 digit , but if you try generate with over 5 digit length, your javascript loop will be crashing.

**Comment by loia5tqd001** [comment]
This is just a small weekly exercise, I haven't expected anyone to read the code or test the project out. I really surprised and delighted when seeing you reported this issue.

About the issue, when seeing it, I have proposed 3 performance fixes: 
- [x] Optimize the main algorithm
- [x] Limit the size of the array could possibly be generated down *(to 9999)*
- [ ] More optimization using asynchronous code/ techniques   

And 2 fixes for the UI experience:
- [x] Make box-shadow transition smoother
- [ ] Change the white background

I have thought it would be not too hard to mark all 5 boxes. But then it ended up to take me tens of hours to write the optimized algorithm correctly, and test it out and finally reduce the time execution *(on my machine)* from taking `300s with array-size of 9999` to `1s with array-size of 10M` *(more will cause js heap out of memory)*. 
async and change background ends up being not relevant.   

---
At the end I have to say I definitely learned so many things after finishing this exercise, thanks to your report. Your work is really valuable, please keep it up. Thank you! :+1:

**Comment by coderschoolreview** [comment]
You did a good job! Thanksanks
